### ISSUE TITLE
1.8 clients only see this

### ISSUE THREAD

**Issue by JSSjogren** [bizarre/Azazel#1]
<img width="1440" alt="screen shot 2018-02-05 at 11 30 00 am" src="https://user-images.githubusercontent.com/25889637/35817644-088467ce-0a6c-11e8-962e-e9fe75c15c9d.png">

This is all 1.8 clients are seeing. 1.7 clients are fine though.

**Comment by JSSjogren** [comment]
Nevermind looks like the issue occurs after you reload with a change. Then when you reload again it goes away... Still something to look into I guess.

**Comment by bizarre** [comment]
Reloading is bad practice and you shouldn’t even be doing it in the first place.
