### ISSUE TITLE
White Nametag

### ISSUE THREAD

**Issue by HappyTNTguy** [bizarre/Azazel#12]
Azazel changes my nametag to white

**Comment by bizarre** [comment]
Steps to reproduce, server version, client version, screenshot

**Comment by HappyTNTguy** [comment]
I just join and it randomly happens.
Server: ExoSpigot 1.7.10 (The one on blackspigot)
 Client Version: 1.7.10
It happens randomly.

**Comment by HappyTNTguy** [comment]
> Steps to reproduce, server version, client version, screenshot

After further testing I was able to recreate it.
https://streamable.com/idleo
